import moment from "moment";
import placeholder from "./pics/profilePic.png";
import placeholder2 from "./pics/pic1.png";

export default function data() {
  return {
    user: { uid: "290" },
    loading: false,
    accountType: "admin",
    address: "5 Beulah Avenue Trans Amadi",
    busStop: "amadi round about",
    country: "Nigeria",
    gender: "male",
    id: "837291871a",
    name: "Admin",
    occupation: "none",
    phoneNumber: "07080173071",
    profilePic: "",
    satelliteChurch: "odili road",
    serviceGroup: "Technical",
    state: "Rivers state",
    defaults: {
      serviceGroups: [
        "Children Ministry",
        "Special Care",
        "Miracle Squad",
        "Prayer Squad",
        "Crowd Control",
        "Transport",
        "Safety",
        "Decoration",
        "Praise",
        "Peace Keepers",
        "Medical",
        "Editorial",
        "Technical",
        "Sanctuary",
        "Ushering",
        "Soul Establishment",
      ],
    },
    testimonies: [
      {
        id: "ano1",
        satelliteChurch: "odili road",
        createdAt: moment(),
        text:
          "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory. papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory. papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory. papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
        title: "divine breakthrough",
        userId: "onnon2813ds",
        userName: "Shadrack Ibiso",
      },
      {
        id: "ano1",
        satelliteChurch: "odili road",
        createdAt: moment(),
        text:
          "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
        title: "divine breakthrough",
        userId: "onnon2813ds",
        userName: "Shadrack Ibiso",
      },
      {
        id: "ano1",
        satelliteChurch: "odili road",
        createdAt: moment(),
        text:
          "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
        title: "divine breakthrough",
        userId: "onnon2813ds",
        userName: "Shadrack Ibiso",
      },
      {
        id: "ano1",
        satelliteChurch: "odili road",
        createdAt: moment(),
        text:
          "papa encouraged us to sow into the cathedral roofing project. I obeyed and sowed all my salary for the month of January 2020. Shortly after, God blesed me with a house and I was also sponsored by my organization for a training in India. I give God all the Glory.",
        title: "divine breakthrough",
        userId: "onnon2813ds",
        userName: "Shadrack Ibiso",
      },
    ],
    soulsWon: [
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "1",
        name: "Shadrack Ibiso Deipriye Godswill",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
        wonBy: {
          id: "213",
          name: "shadrack",
          satelliteChurch: "odili road",
        },
        wonThrough: "evangelism",
        serviceGroup: "technical",
        journeyClass: {
          journey101: true,
          journey201: true,
          journey301: false,
          journey401: false,
        },
        verified: true,
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "2",
        name: "Shadrack Ibiso Deipriye Godswill",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
        wonBy: {
          id: "213",
          name: "shadrack",
          satelliteChurch: "odili road",
        },
        wonThrough: "evangelism",
        serviceGroup: "technical",
        journeyClass: {
          journey101: true,
          journey201: false,
          journey301: false,
          journey401: false,
        },
        verified: false,
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "3",
        name: "Shadrack Ibiso Deipriye Godswill",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi..",
        wonBy: {
          id: "213",
          name: "shadrack",
          satelliteChurch: "odili road",
        },
        wonThrough: "evangelism",
        serviceGroup: "technical",
        journeyClass: {
          journey101: true,
          journey201: false,
          journey301: false,
          journey401: false,
        },
        verified: false,
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "4",
        name: "Shadrack Ibiso Deipriye Godswill",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
        wonBy: {
          id: "213",
          name: "shadrack",
          satelliteChurch: "odili road",
        },
        wonThrough: "evangelism",
        serviceGroup: "technical",
        journeyClass: {
          journey101: true,
          journey201: false,
          journey301: false,
          journey401: false,
        },
        verified: false,
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "5",
        name: "Shadrack Ibiso Deipriye",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
        wonBy: {
          id: "213",
          name: "shadrack",
          satelliteChurch: "odili road",
        },
        wonThrough: "evangelism",
        serviceGroup: "technical",
        journeyClass: {
          journey101: true,
          journey201: false,
          journey301: false,
          journey401: false,
        },
        verified: false,
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "6",
        name: "Shadrack Ibiso Deipriye",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
        wonBy: {
          id: "213",
          name: "shadrack",
          satelliteChurch: "odili road",
        },
        wonThrough: "evangelism",
        serviceGroup: "technical",
        journeyClass: {
          journey101: true,
          journey201: false,
          journey301: false,
          journey401: false,
        },
        verified: false,
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "7",
        name: "Shadrack Ibiso Deipriye",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
        wonBy: {
          id: "213",
          name: "shadrack",
          satelliteChurch: "odili road",
        },
        wonThrough: "altarCall",
        serviceGroup: "technical",
        journeyClass: {
          journey101: true,
          journey201: false,
          journey301: false,
          journey401: false,
        },
        verified: false,
      },
      {
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "amadi round about",
        createdAt: moment(),
        gender: "male",
        id: "8",
        name: "Shadrack Ibiso Deipriye",
        occupation: "software developer",
        phoneNumber: "07080173071",
        prayerRequest:
          "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
        wonBy: {
          id: "213",
          name: "shadrack",
          satelliteChurch: "odili road",
        },
        wonThrough: "firstTimer",
        serviceGroup: "technical",
        journeyClass: {
          journey101: true,
          journey201: false,
          journey301: false,
          journey401: false,
        },
        verified: false,
      },
    ],
    notifications: [
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
      {
        createdAt: moment(),
        from: "odili road",
        id: "27",
        message: "There would be soul winning on Saturday by 9AM",
      },
    ],
    members: [
      {
        accountType: "admin",
        address: "5 Beulah avenue Trans Amadi Port Harcourt",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Abel Rufus Alfonsos",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "sanctuary",
        state: "Rivers state",
        soulsWon: [
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
        ],
      },
      {
        accountType: "admin",
        address: "demo",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Brenda Adoki",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "ushering",
        state: "Rivers state",
        soulsWon: [
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
        ],
      },
      {
        accountType: "admin",
        address: "demo",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Katherine Samson",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "ushering",
        state: "Rivers state",
        soulsWon: [
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
        ],
      },
      {
        accountType: "admin",
        address: "demo",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Natasha James",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "technical",
        state: "Rivers state",
        soulsWon: [
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
        ],
      },
      {
        accountType: "admin",
        address: "demo",
        busStop: "demo",
        country: "demo",
        gender: "male",
        id: "837291871a",
        name: "Eden Brook",
        createdAt: moment(),
        occupation: "demo",
        phoneNumber: "demo",
        profilePic: "",
        satelliteChurch: "odili road",
        serviceGroup: "technical",
        state: "Rivers state",
        soulsWon: [
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
          {
            address: "5 Beulah avenue Trans Amadi Port Harcourt",
            busStop: "amadi round about",
            createdAt: moment(),
            gender: "male",
            id: "8",
            name: "Shadrack Ibiso Deipriye",
            occupation: "software developer",
            phoneNumber: "07080173071",
            prayerRequest:
              "deLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi.",
            wonBy: {
              id: "213",
              name: "shadrack",
              satelliteChurch: "odili road",
            },
            wonThrough: "firstTimer",
            serviceGroup: "technical",
          },
        ],
      },
    ],
    slideShowPics: [
      { src: placeholder2, id: "1" },
      { src: placeholder, id: "2" },
      { src: placeholder2, id: "3" },
      { src: placeholder, id: "4" },
      { src: placeholder2, id: "5" },
    ],
    sermons: [
      {
        id: "ano1",
        createdAt: moment(),
        text:
          "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans. Ad doctus gubergren duo, mel te postea suavitate. Scripta periculis ei eam, te pro movet reformidans. Vis labore scripta ne, ut alii mediocritatem his. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nibh detracto incorrupte eos eu, iuvaret perfecto eam in, his eu possit dolorum temporibus. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Saepe imperdiet at per, appareat vituperata vix te, pri sint assueverit te.</p>",
        title: "How to communicate with the Holy Spirit",
        scriptures: "Matthew 5:12, Roman 4:3-8",
        author: "Pst Chris Ugoh",
      },
      {
        id: "ano2",
        createdAt: moment(),
        text:
          "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans. Ad doctus gubergren duo, mel te postea suavitate. Scripta periculis ei eam, te pro movet reformidans. Vis labore scripta ne, ut alii mediocritatem his. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nibh detracto incorrupte eos eu, iuvaret perfecto eam in, his eu possit dolorum temporibus. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Saepe imperdiet at per, appareat vituperata vix te, pri sint assueverit te.</p>",
        title: "Importance of Tithing",
        scriptures: "Malachi 1, Luke 2:4",
        author: "Pst Chris Ugoh",
      },
      {
        id: "ano3",
        createdAt: moment(),
        text:
          "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans. Ad doctus gubergren duo, mel te postea suavitate. Scripta periculis ei eam, te pro movet reformidans. Vis labore scripta ne, ut alii mediocritatem his. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nibh detracto incorrupte eos eu, iuvaret perfecto eam in, his eu possit dolorum temporibus. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Saepe imperdiet at per, appareat vituperata vix te, pri sint assueverit te.</p>",
        title: "Gaining Insight from the word",
        scriptures: "Matthew 5:12, Roman 4:3-8",
        author: "Pst Chris Ugoh",
      },
      {
        id: "ano4",
        createdAt: moment(),
        text:
          "<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans. Ad doctus gubergren duo, mel te postea suavitate. Scripta periculis ei eam, te pro movet reformidans. Vis labore scripta ne, ut alii mediocritatem his. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Scripta periculis ei eam, te pro movet reformidans. Offendit eleifend moderatius ex vix, quem odio mazim et qui, purto expetendis cotidieque quo cu, veri persius vituperata ei nec. Vivendum intellegat et qui, ei denique consequuntur vix. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Nibh detracto incorrupte eos eu, iuvaret perfecto eam in, his eu possit dolorum temporibus. Pri posse graeco definitiones cu, id eam populo quaestio adipiscing, usu quod malorum te. Saepe imperdiet at per, appareat vituperata vix te, pri sint assueverit te.</p>",
        title: "Conceive it! power it by faith",
        scriptures: "Malachi 1, Luke 2:4",
        author: "Pst Chris Ugoh",
      },
    ],
  };
}
